### ISSUE TITLE
Works with Braccio arm?

### ISSUE THREAD

**Issue by TNTTheLagger** [cgxeiji/CGx-Gcode-RobotArm#2]
I'm trying to control the Braccio robotic arm with this library but I'm using their own PWM board wich just passes trough some arduino pins for PWM they also have a library to move the arm and do other things.
Is there a way to access the computed angles in each step to move the servos?

**Comment by cgxeiji** [comment]
Hello, I apologize for the late reply. Feel free to modify the following https://github.com/cgxeiji/CGx-Gcode-RobotArm/blob/304fd2f1817f2e2da05b3221aea58d5d28548e6a/src/CGx_Gcode.cpp#L404 line to get the actual values of the solver. I hope this helps you!
